name: Cloud run deploy
on:
  push:
    branches: [ master ]
jobs:
  build-and-deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Build docker image
        run: |
          gcloud builds submit --config ./cloudbuild.yaml \
          --substitutions \
          _SERVICE_NAME=${{ secrets.GCP_APPLICATION }},\
          _INSTANCE_NAME=${{ secrets.GCP_SQL_INSTANCE_NAME }},\
          _REGION=${{ secrets.GCP_REGION }},\
          _SECRET_NAME=${{ secrets.GCP_APPLICATION_MASTER_KEY }}
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: ${{ secrets.GCP_APPLICATION }}
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APPLICATION }}
      - name: Use Output
        run: curl "${{ steps.deploy.outputs.url }}"
          